FROM nginxinc/nginx-unprivileged:stable-alpine-slim

RUN rm -v /etc/nginx/nginx.conf

ADD nginx.conf /etc/nginx/

ADD ServicePulse.Host/app /usr/share/nginx/html/
ADD ServicePulse.Host/app /var/www/html/

EXPOSE 5000

CMD ["/usr/sbin/nginx"]